### ISSUE TITLE
липса на условия на първа група

### ISSUE THREAD

**Issue by taki1ds** [triffon/fp-2022-23#5]
@Andreshk може ли да качиш условията на упр 10,11,14

**Comment by Andreshk** [comment]
- упр.10 беше подготовка за контролно, показвах решенията на няколко често срещани задачки + скицирахме решението на зад.1 от [това](https://docs.google.com/document/d/1Voj2Zk_mij6-aZsvNGJ-iUOIIeFJF0E3uSszXzkbN0M) миналогодишно контролно
- упр.11 беше последното преди Коледната ваканция и импровизирана демонстрация на работа с алгебрични типове и входно-изходни операции в Хаскел. Условия нямаше, това са си записки
- на упр.14 решавахме последните задачи от упр.13 (т.е. предишното). Това се познава по надписите `Зад.6`, `Зад.7` и т.н., както и съвпадащите имена на функциите.

**Comment by taki1ds** [comment]
Благодаря!
